### ISSUE TITLE
Abot is not FIPS compliance

### ISSUE THREAD

**Issue by sjdirect** [sjdirect/abot#156]
This file AbotCrawler\Abot\Core\CompactCrawledUrlRepository.cs uses md5 encryption which incompatible with FIPS, changing it to sha1 encryption fixes the problem.

**Comment by sjdirect** [comment]
The encryption used in this class is not used for security. its used to turn a string url into a number to save space and make the lookup faster.

**Comment by usakgb** [comment]
I totally understand what it's being used for and that it has nothing to do with security in this case, but if you try to run it on a PC with FIPS security enabled, any encryption that is not FIPS compliant will fail/throw an exception.

**Comment by cculver** [comment]
I got a trial to abotx and I'm unable to use the entire library because of this same issue. My computer is forced to FIPS compliancy through group policy and I'm unable to change the setting which causes this exception. GetHashCode() would be just as fast and effective for URLs and would not cause this issue. I'm unable to use the library because of this issue. Here are some details:

On the event CrawlerEngine.SiteCrawlCompleted firing, SiteCrawlCompletedArgs.CrawledSite.CrawlResult.ErrorException holds the following InnerException:
"This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms." which is thrown by the System.Security.Cryptography.MD5CryptoServiceProvider constructor. To reproduce, enable FIPS on your computer by following the instructions here: [https://medium.com/@pnpasif/enabling-fips-140-2-on-windows-10-520673c030a9](https://medium.com/@pnpasif/enabling-fips-140-2-on-windows-10-520673c030a9)

Here is information that will help you temporarily disable it. Note that editing the registry may cause unforeseen problems. [https://support.microsoft.com/en-us/help/811833/system-cryptography-use-fips-compliant-algorithms-for-encryption-hashi](https://support.microsoft.com/en-us/help/811833/system-cryptography-use-fips-compliant-algorithms-for-encryption-hashi)

**Comment by sjdirect** [comment]
Another user suggested just using GetHashCode instead of MD5 which seems to work pretty well. May send out a build soon with this fix which should solve your issue.

**Comment by sjdirect** [comment]
This was fixed and is available in nuget version 1.6.0.20
