### ISSUE TITLE
Will not work with HtmlAgilityPack?

### ISSUE THREAD

**Issue by YodasMyDad** [sjdirect/abot#164]
I was under the impress that if I installed HtmlAgilityPack that this library would work OOTB with it? However, I cannot get it to work.

In the 'Crawler_PageCrawlCompletedAsync' method, if I call 'e.CrawledPage.HtmlDocument' I just keep getting the following error?

System.MissingFieldException occurred
  HResult=0x80131511
  Message=Field not found: 'HtmlAgilityPack.HtmlDocument.OptionMaxNestedChildNodes'.
  Source=Abot
  StackTrace:
   at Abot.Poco.CrawledPage.InitializeHtmlAgilityPackDocument()
   at System.Lazy`1.CreateValue()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Abot.Poco.CrawledPage.get_HtmlDocument()

Has anyone got it working?

**Comment by sjdirect** [comment]
About uses a patched version of HTML agility pack that is installed by the
nuget package. You may need to experiment with installing your hap version
and reinstalling abot.

On Apr 21, 2017 11:25 PM, "Lee" <notifications@github.com> wrote:

I was under the impress that if I installed HtmlAgilityPack that this
library would work OOTB with it? However, I cannot get it to work.

In the 'Crawler_PageCrawlCompletedAsync' method, if I call
'e.CrawledPage.HtmlDocument' I just keep getting the following error?

System.MissingFieldException occurred
HResult=0x80131511
Message=Field not found: 'HtmlAgilityPack.HtmlDocument.
OptionMaxNestedChildNodes'.
Source=Abot
StackTrace:
at Abot.Poco.CrawledPage.InitializeHtmlAgilityPackDocument()
at System.Lazy1.CreateValue() at System.Runtime.ExceptionServic
es.ExceptionDispatchInfo.Throw() at System.Lazy1.get_Value()
at Abot.Poco.CrawledPage.get_HtmlDocument()

Has anyone got it working?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sjdirect/abot/issues/164>, or mute the thread

**Comment by YodasMyDad** [comment]
I've tried uninstalling both and reinstalling... Then changing the order in which they are installed. Still to no avail? Surely if you have the HtmlDocument OOTB it should be tested to work? I realise this is an OS project, but why does it have to use a patched version? I was really excited about using the project, and it seems fantastic... But this has put me off a bit.

**Comment by YodasMyDad** [comment]
I should add I have also tried using different versions of HAP still to no avail...

**Comment by sjdirect** [comment]
Try these posts...

https://groups.google.com/forum/m/#!searchin/abot-web-
crawler/Html$20agility$20pack$20version/abot-web-crawler/HFIWBUntCno

https://github.com/sjdirect/abot/issues/21#event-99813994

Assembly binding redirects will likely help you.

**Comment by YodasMyDad** [comment]
Thanks. I've had to download your patched DLL from that post and reference that. Seems to be the only way to get it to work.

**Comment by Ruffio** [comment]
@YodasMyDad can this be closed?
