### ISSUE TITLE
About  Performances

### ISSUE THREAD

**Issue by LeMoussel** [sjdirect/abot#85]
If you start Abot with  a relatively high amount of threads, you get an performance impact and an huge memory footprint.

To optimize Abot to perform thousands of requests per second,  the easiest way is by using Task Parallel Library from the TPL and sync/await programming model (IAsync implementations)
This is in fact the only way to make the Tasks stuff work, starting 10.000. Tasks which using await GetResponseAsync and await GetRequestStreamAsync. 

MSDN Example : [How to: Wrap Event-Based Asynchronous Pattern (EAP) Patterns in a Task](msdn.microsoft.com/en-us/library/ee622454.aspx) 

What do you think ?

**Comment by sjdirect** [comment]
Hi,

Theoretically more requests per seconds for a web crawler is good but you
quickly reach a point of diminishing returns. The problem that most Abot
users hit is cpu bound limits. Abot (as is) will likely crawl fast enough
that it will request pages faster than you can process them due to those
cpu limits. The farther ahead the crawler gets of the code that processes
those pages, the more resources (memory mostly) that will accumulate. Then
you end up in the same situation as you see now (large memory footprint)
but also stability issues. I'm not saying there aren't benefits to what you
are suggesting, i'm just saying that at this moment if I were to implement
the requests completely async, it likely would only help with the initial
memory footprint but cause other issues, like tens of thousands of crawled
pages (and growing) that are waiting to be processed but not enough cpu
power to process them. Eventually the system would run out of memory since
the processing could never keep up with the speed of the requests.

You can even get an idea of that limitation now. If you crank up the
crawler threads really high and register for the
PageCrawlCompletedEvenAsync and do some type of heavy processing. If the
site is big enough 10k pages or above, I would bet that you would either
run out of memory or have some other os stability issue. This may be
something that I do in the future but there are a lot of other
changes/checks that would need to go with it. It really comes down to it is
not worth doing at this moment. The end does not justify the means.

Hope that all makes sense
Steven

**Comment by LeMoussel** [comment]
OK. Thanks for your response.

I think about how to crawl a site with  875713 pages (nodes) and 5105039 links (edges).
One idea would be to store crawled page & links in graph database (as [OrientDB](http://orientdb.com/orientdb/)) not in memory. Thus it should not have out of memory.

**Comment by obender** [comment]
In our project we just Raise ton of small instances of that are cheap, and  use Redis To verify new pages, also We are giving each machine a different start point of the crawled site.
